# Generated by Django 5.1.2 on 2024-10-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
